import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/src/Components/Layouts/Navbar";
import Footer from "@/src/Components/Layouts/Footer";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Hero Kidz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <header className="py-2 md:w-11/12 mx-auto">
          <Navbar></Navbar>
        </header>
        <main className="flex-1 w-11/12 mx-auto">{children}</main>
        <footer className="bg-white border-t border-gray-200">
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
